import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';
const inter = Inter({ subsets: ["latin"] });
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "EduNotion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>


          <NextTopLoader
            color="#000000"
            showSpinner={false}
            showAtBottom={false}
          />
          {children}

        </body>
      </html>
    </ClerkProvider>

  );
}
